# Generated by Django 5.0.1 on 2025-01-22 15:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=30, verbose_name='Название')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('rented_count', models.IntegerField(default=0, verbose_name='Взято')),
                ('condition', models.CharField(choices=[('новый', 'новый'), ('использованный', 'использованный'), ('сломанный', 'сломанный')], max_length=20, verbose_name='Состояние')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентарь',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Applications_repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя')),
                ('Comment', models.CharField(max_length=150, verbose_name='Комментарий')),
                ('Status', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Выполнено', 'Выполнено'), ('Отказано', 'Отказано')], default='На рассмотрении', max_length=100, verbose_name='Статус заявки')),
                ('Request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goods', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Заявка на ремонт',
                'verbose_name_plural': 'Заявки на ремонт',
            },
        ),
        migrations.CreateModel(
            name='Applications_get',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя')),
                ('Request_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Количество')),
                ('Status', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Одобрено', 'Одобрено'), ('Отказано', 'Отказано')], default='На рассмотрении', max_length=100, verbose_name='Статус заявки')),
                ('Request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goods', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Заявка на получение',
                'verbose_name_plural': 'Заявки на получение',
            },
        ),
        migrations.CreateModel(
            name='PurchasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Планируемая цена')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('planned_date', models.DateField(verbose_name='Планируемая дата')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_plans', to='main.goods', verbose_name='Товар')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'План закупки',
                'verbose_name_plural': 'Планы закупок',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Количество')),
                ('Plus', models.BooleanField(default=False, editable=False)),
                ('Rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goods')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
