# Generated by Django 5.0.1 on 2025-01-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_history_alter_applications_get_request_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_good', models.CharField(max_length=30, verbose_name='Название')),
            ],
        ),
    ]
