# Generated by Django 5.0.1 on 2025-01-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_goods_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goods_names', verbose_name='Предмет'),
        ),
    ]
