# Generated by Django 5.0.1 on 2025-01-24 17:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_goods_names_options_remove_users_plus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='condition_after',
            field=models.CharField(blank=True, choices=[('новый', 'новый'), ('использованный', 'использованный'), ('сломанный', 'сломанный')], max_length=20, null=True, verbose_name='Состояние после'),
        ),
        migrations.AddField(
            model_name='history',
            name='condition_before',
            field=models.CharField(blank=True, choices=[('новый', 'новый'), ('использованный', 'использованный'), ('сломанный', 'сломанный')], max_length=20, null=True, verbose_name='Состояние до'),
        ),
        migrations.AddField(
            model_name='history',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='history',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goods_names', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='history',
            name='rented_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Взято'),
        ),
        migrations.AddField(
            model_name='history',
            name='returned_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Возвращено'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores2', to=settings.AUTH_USER_MODEL),
        ),
    ]
