# Generated by Django 5.0.1 on 2025-01-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_history_condition_after_history_condition_before_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.RenameField(
            model_name='history',
            old_name='count',
            new_name='Count',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='goods',
            new_name='Rent',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='history',
            name='condition_after',
        ),
        migrations.RemoveField(
            model_name='history',
            name='condition_before',
        ),
    ]
