# Generated by Django 5.0.1 on 2025-01-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_history_options_rename_count_history_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='history',
            name='Rent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='history',
            name='User',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
