# Generated by Django 5.0.1 on 2025-01-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_history_count_alter_history_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Возвращено'),
        ),
    ]
