# Generated by Django 5.0.1 on 2025-01-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_history_returned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='returned_at',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Возвращено'),
        ),
    ]
