# Generated by Django 5.0.1 on 2025-01-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_history_returned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications_get',
            name='Request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.goods', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='applications_repair',
            name='Request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.goods', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.goods_names', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='history',
            name='Rent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.goods'),
        ),
    ]
