# Generated by Django 5.0.1 on 2025-01-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_applications_get_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.goods', verbose_name='Предмет'),
        ),
    ]
