# Generated by Django 5.0.1 on 2025-01-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_history_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='condition_after',
            field=models.CharField(blank=True, choices=[('новый', 'новый'), ('использованный', 'использованный'), ('сломанный', 'сломанный')], max_length=20, null=True, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='history',
            name='condition_before',
            field=models.CharField(blank=True, choices=[('новый', 'новый'), ('использованный', 'использованный'), ('сломанный', 'сломанный')], max_length=20, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='history',
            name='returned_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Возвращено'),
        ),
    ]
