# Generated by Django 5.0.1 on 2025-01-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_history_condition_after_history_condition_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='condition_after',
            field=models.CharField(blank=True, choices=[('новый', 'новый'), ('использованный', 'использованный'), ('сломанный', 'сломанный')], max_length=20, null=True, verbose_name='Состояние после'),
        ),
        migrations.AlterField(
            model_name='history',
            name='condition_before',
            field=models.CharField(blank=True, choices=[('новый', 'новый'), ('использованный', 'использованный'), ('сломанный', 'сломанный')], max_length=20, null=True, verbose_name='Состояние до'),
        ),
        migrations.AlterField(
            model_name='history',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Возвращено'),
        ),
    ]
