# Generated by Django 5.0.1 on 2025-01-24 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_history_condition_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='rented_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Взято'),
        ),
        migrations.AlterField(
            model_name='history',
            name='returned_at',
            field=models.DateField(blank=True, null=True, verbose_name='Возвращено'),
        ),
    ]
