# Generated by Django 5.0.1 on 2025-01-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_history_rented_at_alter_history_returned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='description',
        ),
    ]
