# Generated by Django 5.0.1 on 2025-01-26 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_goods_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='rented_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Взято'),
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='planned_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Планируемая цена'),
        ),
    ]
