# Generated by Django 5.0.1 on 2025-01-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_goods_count_alter_goods_rented_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Rent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.goods'),
        ),
    ]
